### ISSUE TITLE
[🌎 Feature] github action을 활용한 파일 자동 병합

### ISSUE THREAD

**Issue by egg528** [bandibook/bandibook#20]
## 기능 정의
- notes에 각자 정리한 글을 올리면 pages에 병합된 파일이 자동으로 추가되어야 한다.

**Comment by Doeunnkimm** [comment]
🙏🏽!!!!

**Comment by egg528** [comment]
@Doeunnkimm @hjy0951 
- notes의 디렉토리 위계구조 책 이름 > 팀원 이름으로 변경해도 괜찮은지 확인 부탁드립니다

**Comment by Doeunnkimm** [comment]
@egg528 아주 좋아유 🚀 고우고우
