### ISSUE TITLE
책 제목 오타

### ISSUE THREAD

**Issue by Doeunnkimm** [bandibook/bandibook#25]
@ManHyuk @egg528 

as-is
```
쏙쏙 들어온 함수형 코딩
```

to-be
```
쏙쏙 들어오는 함수형 코딩
```

![image](https://github.com/bandibook/bandibook/assets/112946860/ea16aea3-2aee-4743-8aca-98d98e96bdb3)

**Comment by ManHyuk** [comment]
이미 쏙쏙 들어와있을수도 있는거잖아요....

**Comment by egg528** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
