### ISSUE TITLE
bug: 자동 병합

### ISSUE THREAD

**Issue by Doeunnkimm** [bandibook/bandibook#29]
https://github.com/bandibook/bandibook/pull/28 에 `notes/react-deep-dive/이름` 으로 생성해서 넣었는데

https://github.com/bandibook/bandibook/commit/92aa067cc725212b899fbc93122c27cd07b18b84 돌고 병합된 파일이 생성되지 않은 것 같은데

이게 초기 폴더가 존재하지 않아서인지? 아니면 병합이 제대로 안 된건지? 파악 한번만 해줄 수 있어 ?

**Comment by bandibookk** [comment]
@Doeunnkimm 
도은아 나 반디북인데 내가 고쳐뒀어 😄 
책 열심히 읽으렴!

**Comment by Doeunnkimm** [comment]
@bandibookk 반디북아~ 고마워 아주 잘되었다! 🎉
